In [17]:
#'01_numpy.ipynb'

- 데이터분석: 데이터를 분석하여 의사결정에 도움을 준다.
- 통계 vs 데이터분석 vs 머신러닝
    -통계: 데이터를 요약,해석하는 수학(평균,분산)
    -데이터분석: 문제를 정의하고 인사이트 도출(고객 구매 패턴분석)
    -머신러닝:데이터를 학습하여 **예측** (스팸함 분류, 추천)
-데이터분석: 데이터를 분석하여 의사결정에 도움을 준다 .
    - 의사결정 데이터 기반의 근거 
    -패턴발견,예측(머신러닝)

-DA FLOW(흐름)
1.문제정의
2.데이터수집
3.데이터정제
4.탐색-시각화(결측치,이상치 처리 )
5.통계분석 및 해석(수학 -> 가설 검정,회귀분석)
6.결론도출 

-시트 vs DB VS python 
    -시트는 편함.
    -DB는 대용량 CRUD 처 (억단위)
    -파이썬 시각화 ,분석,머신러닝

- 라이브러리
    -'numpy':빠름(배열연산) 파이썬 리스트 vs Numpy 배열 차이점
    -'pandas':표(DataFrame)-> 'numpy'기반으로 만들어짐
    'matplotlib': 시각화 기본(그래프
    'seaborn': 시각화 심화



SyntaxError: illegal target for annotation (852111171.py, line 3)

In [ ]:
%pip install numpy

In [ ]:
python_list=[1,2,3,4,5]
# [2,4,6,8,10]
result= [x*2 for x in python_list]
print(result)

[2, 4, 6, 8, 10]


In [ ]:
%pip install numpy

   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   ------------- -------------------------- 4.2/12.8 MB 31.1 MB/s eta 0:00:01
   --------------- ------------------------ 5.0/12.8 MB 17.7 MB/s eta 0:00:01
   ------------------ --------------------- 6.0/12.8 MB 10.3 MB/s eta 0:00:01
   ---------------------- ----------------- 7.3/12.8 MB 10.0 MB/s eta 0:00:01
   ---------------------------------- ----- 11.0/12.8 MB 10.7 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.8 MB 10.4 MB/s eta 0:00:01
   ---------------------------------------- 12.8/12.8 MB 10.1 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
import numpy as np

array = np.array([1,2,3,4,5])
result = array * 2
print(result)

In [ ]:
#실수형 arr
import numpy as np

arr = np.array([1, 2, 3], dtype=float)



In [ ]:
import numpy as np  # NumPy를 사용하려면 먼저 import 해야 합니다.

# range: 0부터 10까지 2 간격으로 생성 (0, 2, 4, 6, 8)
range_arr = np.arange(0, 10, 2)
print("range:", range_arr)

# linspace: 0부터 1까지 5개의 등간격 실수 배열 생성
lin_space = np.linspace(0, 1, 5)
print("linspace:", lin_space)

# logspace: 10^0 부터 10^2까지 로그 스케일로 5개 값 생성
log_space = np.logspace(0, 2, 5)
print("logspace:", log_space)


range: [0 2 4 6 8]
linspace: [0.   0.25 0.5  0.75 1.  ]
logspace: [  1.           3.16227766  10.          31.6227766  100.        ]


In [ ]:
#난수 배열 
random= np.random.rand(3,3) #0~1실수
print(random)
#*정규 분포 난수 
normal = np.random.randn(3,3)
print(normal)

#정수 난수(0~9,3*3)
int_random.seed(42) #랜덤 상황42고정
print(int_random)

#시드 설정(랜덤 재현 가능)
np.random.seed(42) # 랜덤 상황 42고정 
np.random.rand(3)



[[0.23615878 0.34850396 0.8963349 ]
 [0.04662542 0.58230081 0.89762702]
 [0.72123809 0.33336958 0.53099282]]
[[ 1.1955303  -0.58276873 -0.20860564]
 [ 0.29955818 -0.67696086 -1.01309551]
 [-0.5759643   0.22364468 -1.08064091]]


NameError: name 'int_random' is not defined

In [ ]:
#배열의 데이터 타입
#데이터 타입확인
arr= np.array([1,2,3])
print(arr.dtype)

#데이터 타입 지정 생성
f_arr = np.array([1,2,3],dtype=np.float64
print(f_arr.dtype)

#데이터 타입 변경 (int - > float)
converted = arr.astype(np.float32)
print(converted.dtype)
#문자열 -> 숫자
str_arr = np.array(['1.2','2.3',
                 


In [ ]:
# 배열 재구성 
arr = np.arange(12)
reshaped= arr.reshape(3,4)
print(reshaped2d)

reshaped3d = arr.reshape(2,2,3) #2페이지,2row *3col
prnt(reshaped3d)

#자동계산
auto1=arr.reshape(3,-1)
auto2=arr.reshape(-1,6)

NameError: name 'reshaped2d' is not defined

In [ ]:
#reshape -> 원본 그대로 ,새로운 배열만들

In [ ]:
# 1~15 정수배열
print(np.arrange(1,16),np.array(range(1,16)))
#0~9까지 홀수
print(np.arrange(1,10,2))

#0~3까지 균등 6등분(5구간) 배열
print(np.linspace(o,3,6))

In [ ]:
#4 *4 단위 행렬(identity matrix) -> 대각선1,나머지0
print(np.eye(4))
#3* 4 사이즈의 1로 가득찬 int 배열
np.ones((3,4), dtype=int)

In [ ]:
# 2 * 3 * 4 사이즈 0~1 난수배열 

In [ ]:
# N차원 -> 1차원
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
flattened = arr.flatten()
print(flattened)  # 출력: [1 2 3 4 5 6]


r=arr.ravel()
f=arr.flatten()

r[0]=100
f[0]=-100

print(arr)
print(r,f)

[1 2 3 4 5 6]
[[100   2   3]
 [  4   5   6]]
[100   2   3   4   5   6] [-100    2    3    4    5    6]


***배열의 인덱싱/슬라이싱

In [20]:
arr= np.array([10,20,30,40,50])
# 접근
print(arr[0],arr[2],arr[-1],arr[-2])
      print(arr)

IndentationError: unexpected indent (890595901.py, line 4)